[meta]
src = "util.commands"
version = "0.1.0"
description = "Test my new flip flops"
prog = "foo"
usage = "Take that jive Jack, put it in your pocket 'til I get back"


[echo]
description = "Simple echo function"
arguments = [
    # range(min/max), choices, append (dest=collection), metavar?
    { name = "text", help = "Some dummy text" },
    { name = "mark", type = "str", help = "Final mark" },
]
options = [
    { name = "other-text", short = "o", default = "Panda", dest = "other", help = "Some other dummy text" },
    { name = "delimiter", default = ", ", help = "use DELIM instead of TAB for field delimiter" },
    { name = "num", default = 42, type = "int", help = "some random number to make things pretty" }
]
function = "echo"
help = "echo func"
prog = "foo"


[yes]
description = "Simple yes function"
argument = { name = "text", help = "Some dummy text" }
option = { name = "should-repeat", short = "r", flag = "True", help = "should repeat text 5 times" }
function = "yes"
help = "yes func"


[no]
description = "Simple no function"
argument = { name = "text", nargs="+", help = "Some dummy text" }
options = [
    { name = "should-log", short = "l", flag = "False", default = true, help = "should not log or else..." },
    { name = "other", nargs="+", help = "Some dummy text" }
]
function = "no"
help = "no func"