meta:
  src: util.commands
  prog: foo
  version: 0.1.0
  description: Test my new flip flops
  usage: Take that jive Jack, put it in your pocket 'til I get back
echo:
  description: Simple echo function
  function: echo
  help: echo func
  arguments:
  - help: Some dummy text
    name: text
  - help: Final mark
    name: mark
    type: str
  options:
  - default: "Panda"
    dest: other
    help: Some other dummy text
    name: other-text
    short: o
  - default: ", "
    help: use DELIM instead of TAB for field delimiter
    name: delimiter
  - default: "42"
    help: some random number to make things pretty
    name: num
    type: int
maybe:
  description: Simple maybe function
  function: maybe
  help: maybe func
  argument:
    choices:
    - 3
    - 5
    - 8
    help: Some meaningless number
    name: number
    type: int
  option:
    choices:
    - 1
    - 2
    dest: other
    help: Other marvelous number
    name: other-number
    nargs: "*"
    type: int
'no':
  description: Simple no function
  function: 'no'
  help: no func
  options:
  - default: true
    flag: 'False'
    help: should not log or else...
    name: should-log
    short: l
  - help: Some dummy text
    name: other
    nargs: "+"
  argument:
    help: Some dummy text
    name: text
    nargs: "+"
'yes':
  description: Simple yes function
  function: 'yes'
  help: yes func
  argument:
    help: Some dummy text
    name: text
  option:
    flag: 'True'
    help: should repeat text 5 times
    name: should-repeat
    short: r
